In [1]:
import pandas as pd

In [16]:
data = pd.read_csv('../raw/09_DCIS_IVG_CARATTEV1_09032023122858605.csv')

In [27]:
italia = data[data['Territorio'] == 'Italia']

In [28]:
italia = italia[italia['Tipo di intervento'] != 'totale']

In [29]:
italia = italia[italia['Tipo dato'] == 'interruzioni volontarie della gravidanza']

In [30]:
italia

,ITTER107,Territorio,TIPO_DATO14,Tipo dato,TIPOINT,Tipo di intervento,TERANT,Terapia antalgica,DURATA_A,Settimane di amenorrea,DURATA_B,Età gestazionale,TIME,Seleziona periodo,Value,Flag Codes,Flags
0,IT,Italia,64,interruzioni volontarie della gravidanza,DILCUR,raschiamento,TOT,totale,TOTAL,totale,TOTAL,totale,2012,2012,11657.0,NaN,NaN
1,IT,Italia,64,interruzioni volontarie della gravidanza,DILCUR,raschiamento,TOT,totale,TOTAL,totale,TOTAL,totale,2013,2013,10258.0,NaN,NaN
2,IT,Italia,64,interruzioni volontarie della gravidanza,DILCUR,raschiamento,TOT,totale,TOTAL,totale,TOTAL,totale,2014,2014,8792.0,NaN,NaN
3,IT,Italia,64,interruzioni volontarie della gravidanza,DILCUR,raschiamento,TOT,totale,TOTAL,totale,TOTAL,totale,2015,2015,8749.0,NaN,NaN
4,IT,Italia,64,interruzioni volontarie della gravidanza,DILCUR,raschiamento,TOT,totale,TOTAL,totale,TOTAL,totale,2016,2016,9667.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952,IT,Italia,64,interruzioni volontarie della gravidanza,PROS,somministrazione di sola prostaglandina,TOT,totale,W_GE13,13 settimane e più,TOTAL,totale,2017,2017,800.0,NaN,NaN
953,IT,Italia,64,interruzioni volontarie della gravidanza,PROS,somministrazione di sola prostaglandina,TOT,totale,W_GE13,13 settimane e più,TOTAL,totale,2018,2018,820.0,NaN,NaN
954,IT,Italia,64,interruzioni volontarie della gravidanza,PROS,somministrazione di sola prostaglandina,TOT,totale,W_GE13,13 settimane e più,TOTAL,totale,2019,2019,751.0,NaN,NaN
955,IT,Italia,64,interruzioni volontarie della gravidanza,PROS,somministrazione di sola prostaglandina,TOT,totale,W_GE13,13 settimane e più,TOTAL,totale,2020,2020,753.0,NaN,NaN
956,IT,Italia,64,interruzioni volontarie della gravidanza,PROS,somministrazione di sola prostaglandina,TOT,totale,W_GE13,13 settimane e più,TOTAL,totale,2021,2021,515.0,NaN,NaN

In [22]:
#italia['Value'] = italia['Value'].dropna

In [31]:
italia['Value'] = italia['Value'].astype(int)

In [35]:
italia = italia[italia['Settimane di amenorrea'] == 'totale']

In [43]:
italia.drop(columns = ['ITTER107', 'TIPO_DATO14', 'TERANT', 'DURATA_A', 'DURATA_B', 'Flag Codes', 'Flags'], inplace = True)

/var/folders/33/6_3s22415y18bgznpc1317_40000gp/T/ipykernel_1864/825019514.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  italia.drop(columns = ['ITTER107', 'TIPO_DATO14', 'TERANT', 'DURATA_A', 'DURATA_B', 'Flag Codes', 'Flags'], inplace = True)

In [61]:
italia_pivoted = italia.pivot_table(values = ['Value'],
                            index = ['Territorio', 'TIME'], 
                            columns = ['Tipo di intervento']).reset_index()

In [62]:
italia_pivoted

                   Territorio  TIME                        Value  \
Tipo di intervento                  altre forme di isterosuzione
0                      Italia  2012                      18093.0
1                      Italia  2013                      18490.0
2                      Italia  2014                      18723.0
3                      Italia  2015                      16220.0
4                      Italia  2016                      14205.0
5                      Italia  2017                      12857.0
6                      Italia  2018                      12484.0
7                      Italia  2019                      11940.0
8                      Italia  2020                       9763.0
9                      Italia  2021                       6904.0

                                                                                                           \
Tipo di intervento diverso da raschiamento,metodo di Karman, altre forme di isterosuzione e farmacologico
0                                                              1429.0
1                                                              1550.0
2                                                               651.0
3                                                               542.0
4                                                              1171.0
5                                                              1183.0
6                                                               750.0
7                                                               685.0
8                                                               320.0
9                                                               566.0

                                                               \
Tipo di intervento metodo di Karman non indicato raschiamento
0                           61989.0        344.0      11657.0
1                           58405.0        193.0      10258.0
2                           54059.0        291.0       8792.0
3                           48152.0        222.0       8749.0
4                           44167.0        323.0       9667.0
5                           40540.0        218.0       9280.0
6                           35840.0        105.0       8317.0
7                           31225.0        330.0       7765.0
8                           26776.0        226.0       5664.0
9                           20040.0        211.0       5073.0

                                                                      \
Tipo di intervento somministrazione di mifepristone e prostaglandina
0                                                                NaN
1                                                             8027.0
2                                                            10243.0
3                                                            11112.0
4                                                            13242.0
5                                                            14266.0
6                                                            15970.0
7                                                            17797.0
8                                                            20902.0
9                                                            28615.0

                                                            \
Tipo di intervento somministrazione di sola prostaglandina
0                                                      NaN
1                                                   1396.0
2                                                   1214.0
3                                                   1090.0
4                                                    974.0
5                                                    963.0
6                                                   1020.0
7                                                    919.0
8                                                    919.0
9                                                    698.0


Tipo di intervento somministrazione di solo mifepristone
0                                                    NaN
1                                                 2023.0
2                                                 1427.0
3                                                 1282.0
4                                                 1125.0
5                                                 1190.0
6                                                 1558.0
7                                                 1146.0
8                                                 1187.0
9                                                 1200.0

In [49]:
italia_pivoted.columns

MultiIndex([('Value', ...),
            ('Value', ...),
            ('Value', ...),
            ('Value', ...),
            ('Value', ...),
            ('Value', ...),
            ('Value', ...),
            ('Value', ...)],
           names=[None, 'Tipo di intervento'])

In [63]:
italia_pivoted.columns = ['territory', 'year', 'other kind of vacuum aspiration', 'different from others', 'Karman method', 'not defined', 'dilatation and curettage', 'mifepristone and prostaglandina', 'prostaglandina only','mifepristone only']

In [64]:
italia_pivoted

,territory,year,other kind of vacuum aspiration,different from others,Karman method,not defined,dilatation and curettage,mifepristone and prostaglandina,prostaglandina only,mifepristone only
0,Italia,2012,18093.0,1429.0,61989.0,344.0,11657.0,NaN,NaN,NaN
1,Italia,2013,18490.0,1550.0,58405.0,193.0,10258.0,8027.0,1396.0,2023.0
2,Italia,2014,18723.0,651.0,54059.0,291.0,8792.0,10243.0,1214.0,1427.0
3,Italia,2015,16220.0,542.0,48152.0,222.0,8749.0,11112.0,1090.0,1282.0
4,Italia,2016,14205.0,1171.0,44167.0,323.0,9667.0,13242.0,974.0,1125.0
5,Italia,2017,12857.0,1183.0,40540.0,218.0,9280.0,14266.0,963.0,1190.0
6,Italia,2018,12484.0,750.0,35840.0,105.0,8317.0,15970.0,1020.0,1558.0
7,Italia,2019,11940.0,685.0,31225.0,330.0,7765.0,17797.0,919.0,1146.0
8,Italia,2020,9763.0,320.0,26776.0,226.0,5664.0,20902.0,919.0,1187.0
9,Italia,2021,6904.0,566.0,20040.0,211.0,5073.0,28615.0,698.0,1200.0

In [66]:
italia_melted = italia_pivoted.melt(id_vars = ['territory', 'year'],
    value_vars = ['other kind of vacuum aspiration', 'different from others', 'Karman method', 'not defined', 'dilatation and curettage', 'mifepristone and prostaglandina', 'prostaglandina only','mifepristone only'],
          value_name = 'value')

In [68]:
italia_melted.columns = ['territory', 'year', 'abortion_type', 'value']

In [69]:
italia_melted

   territory  year                    abortion_type    value
0     Italia  2012  other kind of vacuum aspiration  18093.0
1     Italia  2013  other kind of vacuum aspiration  18490.0
2     Italia  2014  other kind of vacuum aspiration  18723.0
3     Italia  2015  other kind of vacuum aspiration  16220.0
4     Italia  2016  other kind of vacuum aspiration  14205.0
..       ...   ...                              ...      ...
75    Italia  2017                mifepristone only   1190.0
76    Italia  2018                mifepristone only   1558.0
77    Italia  2019                mifepristone only   1146.0
78    Italia  2020                mifepristone only   1187.0
79    Italia  2021                mifepristone only   1200.0

[80 rows x 4 columns]

In [70]:
italia_melted.to_csv('../clean_data/09_abortion_type_italy.csv', index = False)

### controlla dataset

In [1]:
import pandas as pd

In [7]:
data = pd.read_csv('../clean_data/not defined.csv')

FileNotFoundError: [Errno 2] No such file or directory: '../clean_data/not defined.csv'

In [3]:
data

   territory  year                    abortion_type    value
0     Italia  2012  other kind of vacuum aspiration  18093.0
1     Italia  2013  other kind of vacuum aspiration  18490.0
2     Italia  2014  other kind of vacuum aspiration  18723.0
3     Italia  2015  other kind of vacuum aspiration  16220.0
4     Italia  2016  other kind of vacuum aspiration  14205.0
..       ...   ...                              ...      ...
75    Italia  2017                mifepristone only   1190.0
76    Italia  2018                mifepristone only   1558.0
77    Italia  2019                mifepristone only   1146.0
78    Italia  2020                mifepristone only   1187.0
79    Italia  2021                mifepristone only   1200.0

[80 rows x 4 columns]

In [6]:
data[data['abortion_type'] == 'different from others']

   territory  year          abortion_type   value
10    Italia  2012  different from others  1429.0
11    Italia  2013  different from others  1550.0
12    Italia  2014  different from others   651.0
13    Italia  2015  different from others   542.0
14    Italia  2016  different from others  1171.0
15    Italia  2017  different from others  1183.0
16    Italia  2018  different from others   750.0
17    Italia  2019  different from others   685.0
18    Italia  2020  different from others   320.0
19    Italia  2021  different from others   566.0